import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Payload-generated. Regenerated by `payload migrate:create`,
    // `generate:types` and `generate:importmap` — never hand-edited, so
    // linting them only produces noise we are not allowed to fix.
    "migrations/**",
    "payload-types.ts",
    "app/(payload)/admin/importMap.js",
  ]),
]);

export default eslintConfig;
