/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    brands: Brand;
    entries: Entry;
    media: Media;
    articles: Article;
    'magazine-issues': MagazineIssue;
    appearances: Appearance;
    pages: Page;
    'site-settings': SiteSetting;
    people: Person;
    films: Film;
    events: Event;
    locations: Location;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    entries: EntriesSelect<false> | EntriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'magazine-issues': MagazineIssuesSelect<false> | MagazineIssuesSelect<true>;
    appearances: AppearancesSelect<false> | AppearancesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    films: FilmsSelect<false> | FilmsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'approver' | 'contributor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * A lens on the one library, not a separate site. Brands appear as a filter in the Library and decide which collections a contributor can edit — they are not pages and have no URL of their own.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * URL segment, e.g. `fampire` → /fampire
   */
  slug: string;
  /**
   * One line, shown on the brand card.
   */
  tagline?: string | null;
  /**
   * Five of the eight worlds shipped with zero assets. Unchecked keeps the card visible but the surface shallow.
   */
  hasAssets?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every collection in the library. Search by title, description or the original folder name; filter by any facet; edit or delete any row. New Collection needs four things — a title, a one-line description, the link, and what kind it is. Everything else can be filled in later. Never migrate, copy or host the client's files; links plus metadata only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entries".
 */
export interface Entry {
  id: number;
  /**
   * Renamed for strangers. '6. 6/26/2025 - UFC/ Aires Tech RoundTable - Vegas' becomes 'UFC × Aires Tech Roundtable — Las Vegas, June 2025'. This renaming IS the product.
   */
  title: string;
  /**
   * The URL for this collection. Changing it breaks links people have already shared.
   */
  slug: string;
  /**
   * One line, human. What is inside and where it came from.
   */
  description: string;
  /**
   * What the asset IS. Required.
   */
  kind:
    | 'b-roll'
    | 'event photography'
    | 'headshots'
    | 'poster'
    | 'logo'
    | 'trailer'
    | 'BTS'
    | 'podcast'
    | 'press'
    | 'magazine'
    | 'document'
    | 'interview'
    | 'audio';
  /**
   * Points at the client's own storage. Use the portable /drive/folders/<id> form — never /drive/u/N/, which encodes a browser account position and breaks for everyone else.
   */
  url: string;
  /**
   * The original URL, when we canonicalised it.
   */
  rewrittenFrom?: string | null;
  /**
   * 324 subjects exist in more than one folder. The duplicates collapse to one entry; their other locations live here.
   */
  alternates?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional cover image for this collection's card. Paste an absolute image URL — it overrides the automatically sampled frame. Leave empty to keep the sampled one.
   */
  previewUrl?: string | null;
  /**
   * Or upload one. Page furniture only — never the client's library files, which always stay in their own storage.
   */
  previewImage?: (number | null) | Media;
  /**
   * For the preview image.
   */
  altText?: string | null;
  /**
   * What it came FROM. The second axis.
   */
  occasion?:
    | (
        | 'premiere'
        | 'book-signing'
        | 'clinic-production'
        | 'conference'
        | 'cover-shoot'
        | 'roundtable'
        | 'speaking'
        | 'festival'
        | 'interview'
        | 'workout'
        | 'podcast'
        | 'unspecified'
      )
    | null;
  /**
   * Which world this belongs to. A label and a filter on the one shared library — it does not hide anything from anyone.
   */
  tenant?: (number | null) | Brand;
  /**
   * Everyone who APPEARS in the material. Crew and rights holders go in their own fields.
   */
  people?: (number | Person)[] | null;
  /**
   * Shot, cut, produced or directed it — not necessarily in frame.
   */
  crew?: (number | Person)[] | null;
  /**
   * From "owned by X" / "courtesy of X" in the source folder.
   */
  rightsHolder?: (number | Person)[] | null;
  film?: (number | null) | Film;
  event?: (number | null) | Event;
  location?: (number | null) | Location;
  year?: number | null;
  dateStart?: string | null;
  /**
   * Multi-day events only.
   */
  dateEnd?: string | null;
  /**
   * 1–8, when this is magazine production work.
   */
  magazineIssue?: number | null;
  /**
   * Free tags. Never a folder path — tags, so one entry can sit under many lenses.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Review priority, drafted from the folder path. 'none' means the path told us nothing — it is NOT a clearance.
   */
  minorRisk?: ('named' | 'context' | 'none') | null;
  /**
   * DRAFT flag. Never treat as decided.
   */
  containsMinor?: boolean | null;
  /**
   * Confirmed by a person. An entry flagged and not confirmed CANNOT be published — the save will be refused.
   */
  containsMinorConfirmed?: boolean | null;
  /**
   * Internal. Who confirmed, and what they checked.
   */
  safetyNote?: string | null;
  sourcePlatform: 'drive' | 'dropbox' | 'pictime' | 'vimeo' | 'youtube' | 'streaming' | 'site' | 'unknown';
  access: 'public' | 'password' | 'request' | 'broken';
  /**
   * Internal only. Passwords live here and are NEVER rendered on a public surface.
   */
  accessNote?: string | null;
  /**
   * 'unchecked' means the sweep has not run, NOT that the link is fine. A Drive folder that returns 200 but redirects to sign-in is not healthy.
   */
  linkStatus?: ('unchecked' | 'ok' | 'gone' | 'login-required' | 'password' | 'timeout' | 'blocked') | null;
  linkStatusDetail?: string | null;
  lastChecked?: string | null;
  fileCount?: number | null;
  dominantMedia?: ('image' | 'video' | 'document' | 'audio' | 'vector' | 'other') | null;
  mediaMix?: {
    image?: number | null;
    video?: number | null;
    document?: number | null;
    audio?: number | null;
    vector?: number | null;
    other?: number | null;
  };
  /**
   * Measured by sampling real thumbnails. Empty means the sampler could not read a frame (a folder of RAW negatives Drive will not render) — NOT a claim of landscape.
   */
  orientation?: ('landscape' | 'portrait' | 'mixed' | 'square') | null;
  /**
   * Pic-Time serves web-resolution only. Print teams need 300 DPI CMYK — flag it rather than pretending otherwise.
   */
  resolutionClass?: ('web' | 'print' | 'unknown') | null;
  /**
   * Share of sampled frames agreeing. 1 = unanimous.
   */
  orientationConfidence?: number | null;
  /**
   * Frames actually read. Under 3 is provisional.
   */
  orientationSamples?: number | null;
  /**
   * Drives the link-unfurl image.
   */
  previewFileId?: string | null;
  folderId?: string | null;
  /**
   * The client's own folder ancestry, verbatim — including their spelling. Kept unaltered so the audit trail does not lie about what we found.
   */
  folderPath?: string | null;
  rawFolderName?: string | null;
  /**
   * How many copies of this subject the crawl found.
   */
  duplicateFolders?: number | null;
  /**
   * Why the importer did or did not put this forward for review.
   */
  importDisposition?: ('publish' | 'merge' | 'reject') | null;
  holdReason?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Images the site itself needs. NOT the client's asset library — that stays in their own storage and is linked, never uploaded.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What is in the picture, for someone who cannot see it. Required — an image with no alt text fails accessibility and unfurls badly.
   */
  alt: string;
  caption?: string | null;
  /**
   * Photographer or source.
   */
  credit?: string | null;
  /**
   * Where this is meant to be used. Helps the next editor pick correctly.
   */
  usage?: ('header' | 'article' | 'brand' | 'portrait' | 'og' | 'other') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  /**
   * TereZa is always spelled with a capital Z — everywhere, including alt text and metadata. Hard client rule.
   */
  name: string;
  /**
   * URL segment. Appears in shareable filter links.
   */
  slug: string;
  /**
   * Other spellings this person is filed under. Search matches these too, so merging duplicates never loses a way of finding someone.
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  /**
   * How to describe them in a caption, e.g. 'Founder', 'Guest'.
   */
  role?: string | null;
  bio?: string | null;
  /**
   * Portrait for this person's tile. Paste an absolute image URL. Overrides the frame borrowed from the catalog.
   */
  portraitUrl?: string | null;
  /**
   * Or upload a portrait.
   */
  portraitImage?: (number | null) | Media;
  /**
   * One of the four Lolli family members.
   */
  isFamily?: boolean | null;
  /**
   * A child. Every entry featuring them needs contains_minor confirmed by a person before it publishes.
   */
  isMinor?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "films".
 */
export interface Film {
  id: number;
  title: string;
  /**
   * URL segment. Appears in shareable filter links.
   */
  slug: string;
  synopsis?: string | null;
  /**
   * Key art for this film's tile. Paste an absolute image URL. Overrides the frame borrowed from the catalog; leave empty to keep borrowing.
   */
  posterUrl?: string | null;
  /**
   * Or upload the key art.
   */
  posterImage?: (number | null) | Media;
  /**
   * Best-documentary awards.
   */
  awards?: number | null;
  year?: number | null;
  status?: ('released' | 'in-production' | 'pre-production') | null;
  /**
   * One line, e.g. 'Six episodes' or 'Five-part flagship'.
   */
  note?: string | null;
  watch?:
    | {
        platform: string;
        url: string;
        /**
         * No paywall.
         */
        free?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * URL segment. Appears in shareable filter links.
   */
  slug: string;
  summary?: string | null;
  startDate?: string | null;
  /**
   * Leave empty for a single-day event.
   */
  endDate?: string | null;
  location?: (number | null) | Location;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  label: string;
  /**
   * URL segment. Appears in shareable filter links.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Press releases, announcements and features written by the team.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL segment.
   */
  slug: string;
  /**
   * Which world this belongs to. A label and a filter on the one shared library — it does not hide anything from anyone.
   */
  tenant?: (number | null) | Brand;
  type?: ('press-release' | 'announcement' | 'feature' | 'statement' | 'coverage') | null;
  publishedAt?: string | null;
  /**
   * One or two sentences. Used on cards and in link previews.
   */
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * For 'coverage elsewhere' — where it was published. Storing the URL is the correct treatment; we never rehost someone else's article.
   */
  externalUrl?: string | null;
  people?: (number | Person)[] | null;
  films?: (number | Film)[] | null;
  events?: (number | Event)[] | null;
  /**
   * Catalog collections a reader should be offered alongside — b-roll for the story, photography from the event.
   */
  relatedCollections?: (number | Entry)[] | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * One record per issue. Cover subject, cover image, and where to read it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazine-issues".
 */
export interface MagazineIssue {
  id: number;
  issueNumber: number;
  title: string;
  /**
   * URL segment.
   */
  slug: string;
  /**
   * Which world this belongs to. A label and a filter on the one shared library — it does not hide anything from anyone.
   */
  tenant?: (number | null) | Brand;
  coverSubject?: (number | null) | Person;
  coverImage?: (number | null) | Media;
  publishedAt?: string | null;
  summary?: string | null;
  /**
   * Where to read it. Leave empty if the client has not supplied a link — two issues currently have none, and an empty field is more honest than a dead one.
   */
  readUrl?: string | null;
  /**
   * Cover shoot and production folders for this issue.
   */
  relatedCollections?: (number | Entry)[] | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  seoImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Podcasts, panels, keynotes and broadcast. Log one in under two minutes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearances".
 */
export interface Appearance {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Which world this belongs to. A label and a filter on the one shared library — it does not hide anything from anyone.
   */
  tenant?: (number | null) | Brand;
  /**
   * Show, publication or venue.
   */
  outlet?: string | null;
  /**
   * Leave empty if the air date is unknown.
   */
  date?: string | null;
  /**
   * Who appeared. Leave empty if the log does not record it.
   */
  people?: (number | Person)[] | null;
  type?: ('podcast' | 'panel' | 'keynote' | 'broadcast' | 'print' | 'conference') | null;
  /**
   * Where to watch or listen.
   */
  url?: string | null;
  summary?: string | null;
  /**
   * Audience figure as the client recorded it. Reproduced verbatim, never estimated.
   */
  views?: number | null;
  /**
   * When that figure was captured, if known.
   */
  viewsAsOf?: string | null;
  /**
   * Still for the log row. An absolute URL from the platform's own thumbnail service — nothing is hosted here.
   */
  thumbnail?: string | null;
  parts?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The site is five pages: the landing page, the Library, Films, People and Press. Open one, and everything on it is a block you can edit, reorder or remove — add a new one with “Add Layout” at the bottom.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * The URL path, e.g. /fampire/press. Leading slash is added for you.
   */
  slug: string;
  /**
   * Which world this belongs to. A label and a filter on the one shared library — it does not hide anything from anyone.
   */
  tenant?: (number | null) | Brand;
  /**
   * Narrative sections embed real collection cards rather than describing them in prose — so a page can never drift out of date relative to the catalog.
   */
  layout: (
    | {
        /**
         * The oversized mark. FAMPIRE.
         */
        wordmark: string;
        /**
         * The claim beside it. Two or three lines.
         */
        headline?: string | null;
        /**
         * Trailing words rendered in grey, as in the approved layout.
         */
        headlineTail?: string | null;
        /**
         * Vertical rail text down the left edge.
         */
        rail?: string | null;
        /**
         * Small paragraph at lower right.
         */
        note?: string | null;
        /**
         * Whose portraits fan across the hero. Leave empty to show the family automatically — then adding a family member in the CMS adds a card here with no page edit.
         */
        people?: (number | Person)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'deckHero';
      }
    | {
        label?: string | null;
        /**
         * Leave empty to show every brand in the CMS, in order.
         */
        brands?: (number | Brand)[] | null;
        /**
         * Scroll the strip. Pauses on hover, and respects reduced-motion.
         */
        marquee?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'brandStrip';
      }
    | {
        /**
         * One line of display type per row.
         */
        lines: {
          text: string;
          id?: string | null;
        }[];
        /**
         * Let the pictures sit behind the words rather than beside them.
         */
        overlap?: boolean | null;
        /**
         * Two people, left and right. Leave empty to use the first two family members, so the section follows the CMS.
         */
        portraits?: (number | Person)[] | null;
        /**
         * Optional short lines beneath, one at each side.
         */
        notes?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Render on the near-black band.
         */
        dark?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statementSplit';
      }
    | {
        eyebrow?: string | null;
        /**
         * The paragraph beside the film.
         */
        intro?: string | null;
        /**
         * A YouTube or Vimeo URL, or a bare Vimeo ID. Leave empty for the still poster. Note: a Vimeo video whose privacy settings disable embedding will refuse to play on any site — the page falls back to the poster.
         */
        videoId?: string | null;
        /**
         * Seconds into the film to start.
         */
        startAt?: number | null;
        /**
         * The figures on the rail. Live sources are recomputed every request.
         */
        stats?:
          | {
              value?: string | null;
              label: string;
              source?: ('manual' | 'entryCount' | 'filmCount' | 'eventCount' | 'fileCount' | 'awardTotal') | null;
              id?: string | null;
            }[]
          | null;
        actions?:
          | {
              label: string;
              href: string;
              emphasis?: ('primary' | 'secondary') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroFeature';
      }
    | {
        /**
         * Small label above the heading.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        media?: ('none' | 'video' | 'image') | null;
        mediaUrl?: string | null;
        actions?:
          | {
              label: string;
              href: string;
              emphasis?: ('primary' | 'secondary') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        body?: string | null;
        /**
         * A quieter second paragraph.
         */
        secondary?: string | null;
        actionLabel?: string | null;
        actionHref?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'statement';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        width?: ('prose' | 'full') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        columns: {
          width?: ('equal' | 'wide' | 'narrow') | null;
          content?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          entries?: (number | Entry)[] | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'columns';
      }
    | {
        spacing?: ('small' | 'medium' | 'large') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'divider';
      }
    | {
        /**
         * Small label above the heading.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        perPage?: number | null;
        /**
         * The filter rail down the left.
         */
        showFacets?: boolean | null;
        showSearch?: boolean | null;
        showSort?: boolean | null;
        showCount?: boolean | null;
        /**
         * Always applied and not removable by the reader. Leave empty for the whole pool.
         */
        locked?: {
          brand?: (number | null) | Brand;
          kind?:
            | (
                | 'b-roll'
                | 'event photography'
                | 'headshots'
                | 'poster'
                | 'logo'
                | 'trailer'
                | 'BTS'
                | 'podcast'
                | 'press'
                | 'magazine'
                | 'document'
                | 'interview'
                | 'audio'
              )[]
            | null;
          orientation?: ('portrait' | 'landscape' | 'square' | 'mixed')[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'libraryBrowser';
      }
    | {
        /**
         * Small label above the heading.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        layout?: ('grid' | 'row' | 'list' | 'spotlight') | null;
        limit?: number | null;
        /**
         * Leave a filter empty to ignore it. Filters combine — two axes at once.
         */
        filters?: {
          kind?:
            | (
                | 'b-roll'
                | 'event photography'
                | 'headshots'
                | 'poster'
                | 'logo'
                | 'trailer'
                | 'BTS'
                | 'podcast'
                | 'press'
                | 'magazine'
                | 'document'
                | 'interview'
                | 'audio'
              )[]
            | null;
          occasion?:
            | (
                | 'premiere'
                | 'book-signing'
                | 'clinic-production'
                | 'conference'
                | 'cover-shoot'
                | 'roundtable'
                | 'speaking'
                | 'festival'
                | 'interview'
                | 'workout'
                | 'podcast'
                | 'unspecified'
              )[]
            | null;
          orientation?: ('portrait' | 'landscape' | 'square' | 'mixed')[] | null;
          brand?: (number | null) | Brand;
          people?: (number | Person)[] | null;
          film?: (number | null) | Film;
          event?: (number | null) | Event;
          location?: (number | null) | Location;
          year?: number | null;
          /**
           * Hide anything flagged as containing a minor, confirmed or not.
           */
          excludeMinors?: boolean | null;
        };
        sort?: ('-fileCount' | '-dateStart' | 'dateStart' | 'title') | null;
        /**
         * Optional link to the same filter in the Library, so the lens opens into the pool.
         */
        viewAll?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'entryQuery';
      }
    | {
        /**
         * Small label above the heading.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        entries: (number | Entry)[];
        layout?: ('grid' | 'row' | 'list') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'entryPicks';
      }
    | {
        /**
         * Small label above the heading.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        /**
         * Leave empty to show the whole slate.
         */
        films?: (number | Film)[] | null;
        layout?: ('list' | 'grid' | 'profiles') | null;
        showWatchLinks?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'filmStrip';
      }
    | {
        /**
         * Small label above the heading.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        /**
         * Leave empty to show the whole family.
         */
        people?: (number | Person)[] | null;
        layout?: ('names' | 'portraits' | 'profiles' | 'roster') | null;
        /**
         * Bios come from Who & What → People, so they are written once and reused.
         */
        showBios?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'peopleRow';
      }
    | {
        /**
         * Small label above the heading.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        /**
         * The fact on the right of the heading.
         */
        aside?: string | null;
        limit?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'magazineShelf';
      }
    | {
        /**
         * Small label above the heading.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        /**
         * The closing note under the matrix. Optional.
         */
        note?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'watchGrid';
      }
    | {
        /**
         * Small label above the heading.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        /**
         * How many of the most-watched appearances lead the page. 0 for none.
         */
        featuredCount?: number | null;
        /**
         * Leave empty for all of them.
         */
        limit?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pressList';
      }
    | {
        /**
         * Small label above the heading.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        lanes: {
          label: string;
          detail?: string | null;
          /**
           * A pre-filtered Library view.
           */
          href: string;
          id?: string | null;
        }[];
        layout?: ('cards' | 'phases') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'lanes';
      }
    | {
        /**
         * Small label above the heading.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        stats?:
          | {
              value: string;
              label: string;
              /**
               * Live values are computed from the catalog at request time, so they cannot go stale.
               */
              source?: ('manual' | 'entryCount' | 'filmCount' | 'filmRecordCount' | 'awardTotal' | 'fileCount') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stats';
      }
    | {
        quote: string;
        attribution?: string | null;
        /**
         * Publication or outlet.
         */
        source?: string | null;
        sourceUrl?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quote';
      }
    | {
        /**
         * Small label above the heading.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        items?:
          | {
              question: string;
              answer: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        /**
         * Small label above the heading.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        variants?:
          | {
              /**
               * e.g. ':30 introduction', 'Short bio'.
               */
              label: string;
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'copyBlock';
      }
    | {
        /**
         * Small label above the heading.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        /**
         * Trailer or reel. Never a gated asset.
         */
        url: string;
        aspect?: ('16-9' | '9-16' | '1-1') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'embed';
      }
    | {
        /**
         * Small label above the heading.
         */
        eyebrow?: string | null;
        heading?: string | null;
        intro?: string | null;
        actions?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        /**
         * No gates on public surfaces — a CTA may link to a contact page, never sit in front of an asset as a form.
         */
        note?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        placeholder?: string | null;
        /**
         * Pre-scope the search. Empty means the whole catalog.
         */
        scope?: {
          orientation?: ('portrait' | 'landscape' | 'square' | 'mixed')[] | null;
          brand?: (number | null) | Brand;
          kind?:
            | (
                | 'b-roll'
                | 'event photography'
                | 'headshots'
                | 'poster'
                | 'logo'
                | 'trailer'
                | 'BTS'
                | 'podcast'
                | 'press'
                | 'magazine'
                | 'document'
                | 'interview'
                | 'audio'
              )[]
            | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'searchBar';
      }
  )[];
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Absolute URL. Real photography only — no stock, no illustration substitutes.
   */
  seoImage?: string | null;
  /**
   * Keep this page out of search engines.
   */
  noIndex?: boolean | null;
  /**
   * Competitors are never named, referenced or disparaged — this includes SEO copy. Hard client rule.
   */
  seoNote?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The links in the masthead and the footer, plus the search placeholder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  label: string;
  /**
   * Which world this belongs to. A label and a filter on the one shared library — it does not hide anything from anyone.
   */
  tenant?: (number | null) | Brand;
  nav?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footer?: {
    blurb?: string | null;
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    /**
     * FAMPIRE®, WYNX®, HNN®, BIOHACK YOURSELF®, World's Top Dentist™.
     */
    trademarkNote?: string | null;
  };
  searchPlaceholder?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'entries';
        value: number | Entry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'magazine-issues';
        value: number | MagazineIssue;
      } | null)
    | ({
        relationTo: 'appearances';
        value: number | Appearance;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'films';
        value: number | Film;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  hasAssets?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entries_select".
 */
export interface EntriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  kind?: T;
  url?: T;
  rewrittenFrom?: T;
  alternates?:
    | T
    | {
        url?: T;
        id?: T;
      };
  previewUrl?: T;
  previewImage?: T;
  altText?: T;
  occasion?: T;
  tenant?: T;
  people?: T;
  crew?: T;
  rightsHolder?: T;
  film?: T;
  event?: T;
  location?: T;
  year?: T;
  dateStart?: T;
  dateEnd?: T;
  magazineIssue?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  minorRisk?: T;
  containsMinor?: T;
  containsMinorConfirmed?: T;
  safetyNote?: T;
  sourcePlatform?: T;
  access?: T;
  accessNote?: T;
  linkStatus?: T;
  linkStatusDetail?: T;
  lastChecked?: T;
  fileCount?: T;
  dominantMedia?: T;
  mediaMix?:
    | T
    | {
        image?: T;
        video?: T;
        document?: T;
        audio?: T;
        vector?: T;
        other?: T;
      };
  orientation?: T;
  resolutionClass?: T;
  orientationConfidence?: T;
  orientationSamples?: T;
  previewFileId?: T;
  folderId?: T;
  folderPath?: T;
  rawFolderName?: T;
  duplicateFolders?: T;
  importDisposition?: T;
  holdReason?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  usage?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tenant?: T;
  type?: T;
  publishedAt?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  externalUrl?: T;
  people?: T;
  films?: T;
  events?: T;
  relatedCollections?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "magazine-issues_select".
 */
export interface MagazineIssuesSelect<T extends boolean = true> {
  issueNumber?: T;
  title?: T;
  slug?: T;
  tenant?: T;
  coverSubject?: T;
  coverImage?: T;
  publishedAt?: T;
  summary?: T;
  readUrl?: T;
  relatedCollections?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearances_select".
 */
export interface AppearancesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  tenant?: T;
  outlet?: T;
  date?: T;
  people?: T;
  type?: T;
  url?: T;
  summary?: T;
  views?: T;
  viewsAsOf?: T;
  thumbnail?: T;
  parts?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tenant?: T;
  layout?:
    | T
    | {
        deckHero?:
          | T
          | {
              wordmark?: T;
              headline?: T;
              headlineTail?: T;
              rail?: T;
              note?: T;
              people?: T;
              id?: T;
              blockName?: T;
            };
        brandStrip?:
          | T
          | {
              label?: T;
              brands?: T;
              marquee?: T;
              id?: T;
              blockName?: T;
            };
        statementSplit?:
          | T
          | {
              lines?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              overlap?: T;
              portraits?: T;
              notes?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              dark?: T;
              id?: T;
              blockName?: T;
            };
        heroFeature?:
          | T
          | {
              eyebrow?: T;
              intro?: T;
              videoId?: T;
              startAt?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    source?: T;
                    id?: T;
                  };
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    emphasis?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              media?: T;
              mediaUrl?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    emphasis?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statement?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              secondary?: T;
              actionLabel?: T;
              actionHref?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        columns?:
          | T
          | {
              columns?:
                | T
                | {
                    width?: T;
                    content?: T;
                    entries?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              spacing?: T;
              id?: T;
              blockName?: T;
            };
        libraryBrowser?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              perPage?: T;
              showFacets?: T;
              showSearch?: T;
              showSort?: T;
              showCount?: T;
              locked?:
                | T
                | {
                    brand?: T;
                    kind?: T;
                    orientation?: T;
                  };
              id?: T;
              blockName?: T;
            };
        entryQuery?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              layout?: T;
              limit?: T;
              filters?:
                | T
                | {
                    kind?: T;
                    occasion?: T;
                    orientation?: T;
                    brand?: T;
                    people?: T;
                    film?: T;
                    event?: T;
                    location?: T;
                    year?: T;
                    excludeMinors?: T;
                  };
              sort?: T;
              viewAll?: T;
              id?: T;
              blockName?: T;
            };
        entryPicks?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              entries?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        filmStrip?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              films?: T;
              layout?: T;
              showWatchLinks?: T;
              id?: T;
              blockName?: T;
            };
        peopleRow?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              people?: T;
              layout?: T;
              showBios?: T;
              id?: T;
              blockName?: T;
            };
        magazineShelf?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              aside?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        watchGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              note?: T;
              id?: T;
              blockName?: T;
            };
        pressList?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              featuredCount?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        lanes?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              lanes?:
                | T
                | {
                    label?: T;
                    detail?: T;
                    href?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    source?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              source?: T;
              sourceUrl?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        copyBlock?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              variants?:
                | T
                | {
                    label?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              url?: T;
              aspect?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
              note?: T;
              id?: T;
              blockName?: T;
            };
        searchBar?:
          | T
          | {
              placeholder?: T;
              scope?:
                | T
                | {
                    orientation?: T;
                    brand?: T;
                    kind?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  seoImage?: T;
  noIndex?: T;
  seoNote?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  label?: T;
  tenant?: T;
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footer?:
    | T
    | {
        blurb?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        trademarkNote?: T;
      };
  searchPlaceholder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  role?: T;
  bio?: T;
  portraitUrl?: T;
  portraitImage?: T;
  isFamily?: T;
  isMinor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "films_select".
 */
export interface FilmsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  synopsis?: T;
  posterUrl?: T;
  posterImage?: T;
  awards?: T;
  year?: T;
  status?: T;
  note?: T;
  watch?:
    | T
    | {
        platform?: T;
        url?: T;
        free?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}