import catalogJson from "@/data/fampire/catalog.json";

/**
 * The FAMPIRE catalog: a read layer over data/fampire/catalog.json, which is
 * generated by scripts/fampire/build-catalog.mjs from the client's own B-Roll
 * Asset Library and media-kit page. Nothing here hosts a file — every entry is
 * a described pointer at storage the client already owns.
 *
 * Deliberately a static import rather than a DB read: the whole catalog is a
 * few hundred rows of text, so search runs in-process against an array and
 * returns in single-digit milliseconds. Prove retrieval feels instant before
 * paying for a query layer (build plan §12, stage 2).
 */

export type Platform =
  | "drive" | "dropbox" | "pictime" | "vimeo" | "youtube" | "streaming" | "site" | "unknown";

export type Access = "public" | "password" | "request" | "broken";

export type Kind =
  | "b-roll" | "event photography" | "headshots" | "poster" | "logo"
  | "trailer" | "BTS" | "podcast" | "press" | "magazine" | "document";

export type Subject = "anthony" | "tereza" | "love" | "legend" | (string & {});

export type Entry = {
  id: string;
  title: string;
  description: string;
  url: string;
  /** Original URL, when we rewrote an account-scoped or tracking-laden one. */
  rewritten_from: string | null;
  alternates: string[];
  preview: string | null;
  source_platform: Platform;
  access: Access;
  visibility: "public" | "private";
  kind: Kind;
  subjects: Subject[];
  brands: string[];
  film: string | null;
  event: string | null;
  year: number | null;
  /** DRAFT flag. Never treat as decided — see contains_minor_confirmed. */
  contains_minor: boolean;
  contains_minor_confirmed: boolean;
  image: string | null;
  /** Up to four more frames from the same folder — a contact sheet, not a crop. */
  strip: string[];
  /** Every frame in the folder is a flat fill (chroma plate, transparent logo):
   *  show it contained on the paper ground, never cover-cropped. */
  image_flat: boolean;
  /** How we got the picture: drive-folder | drive-file | vimeo | youtube | og |
   *  dropbox-file | borrowed-film-art. Null when there is none. */
  image_source: string | null;
  source_page: string | null;
  /** Written by scripts/fampire/check-links.mjs. `unchecked` means the sweep
   *  has not run, NOT that the link is fine. */
  status:
    | "unchecked" | "ok" | "gone" | "login-required"
    | "password" | "timeout" | "blocked";
  /** Why, in one phrase — shown to the internal team, not to the public. */
  status_detail: string | null;
  last_checked: string | null;
};

export type WatchLink = { film: string; platform: string; url: string; free: boolean };

const catalog = catalogJson as unknown as { entries: Entry[]; where_to_watch: WatchLink[] };

export const ENTRIES: Entry[] = catalog.entries;
export const WHERE_TO_WATCH: WatchLink[] = catalog.where_to_watch;

/** Entries a signed-out visitor may see. Everything else needs a session. */
export const PUBLIC_ENTRIES = ENTRIES.filter((e) => e.visibility === "public");

export function visibleEntries(signedIn: boolean): Entry[] {
  return signedIn ? ENTRIES : PUBLIC_ENTRIES;
}

// ── Presentation labels ─────────────────────────────────────────────────

export const SUBJECT_LABEL: Record<string, string> = {
  anthony: "Anthony Lolli",
  // TereZa is always spelled with a capital Z — everywhere, including alt
  // text and metadata. Hard rule from the client.
  tereza: "TereZa Hakobyan-Lolli",
  love: "Love Lolli",
  legend: "Legend Lolli",
};

export const BRAND_LABEL: Record<string, string> = {
  "biohack-yourself": "Biohack Yourself",
  "lolli-brands": "Lolli Brands Entertainment",
  "lolli-holdings": "Lolli Holdings",
  hnn: "HNN",
};

export const PLATFORM_LABEL: Record<Platform, string> = {
  drive: "Google Drive",
  dropbox: "Dropbox",
  pictime: "Pic-Time",
  vimeo: "Vimeo",
  youtube: "YouTube",
  streaming: "Streaming",
  site: "Web",
  unknown: "—",
};

// ── Facets ──────────────────────────────────────────────────────────────

export type Facets = {
  q?: string;
  kind?: string;
  subject?: string;
  year?: string;
  brand?: string;
  film?: string;
  event?: string;
};

/** Every filter state is URL-addressable — this is the parse half of that. */
export function facetsFromParams(params: Record<string, string | string[] | undefined>): Facets {
  const one = (v: string | string[] | undefined) => (Array.isArray(v) ? v[0] : v) || undefined;
  return {
    q: one(params.q),
    kind: one(params.kind),
    subject: one(params.subject),
    year: one(params.year),
    brand: one(params.brand),
    film: one(params.film),
    event: one(params.event),
  };
}

/** And this is the serialise half. Empty values drop out, so URLs stay clean. */
export function facetsToQuery(f: Facets): string {
  const p = new URLSearchParams();
  for (const [k, v] of Object.entries(f)) if (v) p.set(k, v);
  const s = p.toString();
  return s ? `?${s}` : "";
}

/**
 * Search vocabulary bridging.
 *
 * The catalog speaks production language — `b-roll`, `event photography`,
 * `BTS` — and a journalist on deadline types press language: "clips",
 * "photos", "behind the scenes", "kids". Measured against a battery of
 * realistic queries, twelve of fifty-eight returned nothing, and almost all of
 * those were vocabulary mismatches rather than genuinely absent material.
 *
 * These are folded into each entry's index text at module load, so the match
 * stays a plain substring test — no scoring, no fuzzy library, nothing to tune.
 */
const KIND_ALIASES: Record<string, string> = {
  "b-roll": "broll clips footage video videos raw cutaway",
  "event photography": "photos photography stills pictures pics gallery galleries shoot",
  headshots: "headshot portrait portraits bio bios profile",
  poster: "posters key art artwork keyart onesheet",
  logo: "logos wordmark mark marks identity branding",
  trailer: "trailers teaser teasers promo",
  BTS: "bts behind the scenes making of production",
  magazine: "magazines issue issues print editorial cover covers",
  press: "press coverage article articles news media",
  podcast: "podcasts episode episodes audio interview interviews",
  document: "documents doc docs pdf paperwork",
};

/** Children are searched for by relationship far more than by name. */
const SUBJECT_ALIASES: Record<string, string> = {
  love: "kids children child daughter family",
  legend: "kids children child son family",
  anthony: "family couple parents founder",
  tereza: "family couple parents",
};

/** Punctuation is noise here: `b-roll` and `broll`, `TereZa` and `tereza`, and
 *  `Bye Ol' Dentistry` and `bye ol dentistry` must all be the same token. */
function normalize(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

function haystack(e: Entry): string {
  return normalize(
    [
      e.title,
      e.description,
      e.film,
      e.event,
      e.kind,
      KIND_ALIASES[e.kind],
      ...e.subjects.map((s) => `${SUBJECT_LABEL[s] ?? s} ${SUBJECT_ALIASES[s] ?? ""}`),
      ...e.brands.map((b) => BRAND_LABEL[b] ?? b),
      PLATFORM_LABEL[e.source_platform],
      e.year,
    ]
      .filter(Boolean)
      .join(" "),
  );
}

/** Built once — 94 rows of text, so there is nothing to gain from laziness. */
const INDEX = new Map<string, string>(ENTRIES.map((e) => [e.id, haystack(e)]));

/**
 * Every term must match somewhere, so "tereza 2025" narrows rather than
 * widening — which is what someone typing two words actually means.
 *
 * Singular and plural are treated as the same word. Not stemming properly,
 * just testing the term with and without a trailing "s": that covers
 * photo/photos, trailer/trailers, logo/logos and bio/bios, which is the whole
 * of the observed problem, without dragging in a stemmer that would also
 * conflate things a reader meant to keep apart.
 */
function matches(h: string, term: string): boolean {
  if (h.includes(term)) return true;
  if (term.length > 3 && term.endsWith("s") && h.includes(term.slice(0, -1))) return true;
  if (term.length > 2 && h.includes(`${term}s`)) return true;
  return false;
}

function search(entries: Entry[], q: string | undefined): Entry[] {
  const terms = normalize(q ?? "").split(" ").filter(Boolean);
  if (!terms.length) return entries;
  return entries.filter((e) => {
    const h = INDEX.get(e.id) ?? haystack(e);
    return terms.every((t) => matches(h, t));
  });
}

export function applyFacets(entries: Entry[], f: Facets): Entry[] {
  let out = search(entries, f.q);
  if (f.kind) out = out.filter((e) => e.kind === f.kind);
  if (f.subject) out = out.filter((e) => e.subjects.includes(f.subject!));
  if (f.year) out = out.filter((e) => String(e.year) === f.year);
  if (f.brand) out = out.filter((e) => e.brands.includes(f.brand!));
  if (f.film) out = out.filter((e) => e.film === f.film);
  if (f.event) out = out.filter((e) => e.event === f.event);
  return out;
}

/**
 * Counts are computed against the set filtered by every OTHER facet, so a
 * facet value showing "6" always yields 6 results when clicked, and options
 * that would yield nothing disappear instead of becoming dead ends.
 */
export function facetCounts(entries: Entry[], f: Facets, axis: keyof Facets): [string, number][] {
  const rest: Facets = { ...f, [axis]: undefined };
  const pool = applyFacets(entries, rest);
  const counts = new Map<string, number>();
  const bump = (k: string | number | null) => {
    if (k === null || k === undefined || k === "") return;
    const key = String(k);
    counts.set(key, (counts.get(key) ?? 0) + 1);
  };

  for (const e of pool) {
    if (axis === "kind") bump(e.kind);
    else if (axis === "subject") e.subjects.forEach(bump);
    else if (axis === "year") bump(e.year);
    else if (axis === "brand") e.brands.forEach(bump);
    else if (axis === "film") bump(e.film);
    else if (axis === "event") bump(e.event);
  }

  return [...counts.entries()].sort((a, b) =>
    axis === "year" ? b[0].localeCompare(a[0]) : b[1] - a[1] || a[0].localeCompare(b[0]),
  );
}

// ── Curated lenses over the same pool ───────────────────────────────────
// Sections are lenses; the Library is the pool. A collection is never
// duplicated, only seen from more than one angle.

export const FILMS = [
  { slug: "biohack-yourself", title: "Biohack Yourself", awards: 16, note: "Five-part flagship", year: 2024 },
  { slug: "the-guru", title: "The Guru", awards: 19, note: "Most decorated on the slate", year: 2024 },
  { slug: "skin-deep", title: "Skin Deep", awards: 13, note: "Feature documentary", year: 2023 },
  { slug: "the-super-lollis", title: "The Super Lollis", awards: 13, note: "Six episodes", year: 2022 },
  { slug: "from-fat-lolli", title: "From Fat Lolli to 6 Pack Lolli", awards: 4, note: "The origin story", year: 2020 },
  { slug: "shealed", title: "sHEALed", awards: 3, note: "Four parts · releasing 2026", year: 2026 },
  { slug: "bye-ol-dentistry", title: "Bye Ol' Dentistry", awards: 0, note: "In production", year: 2026 },
  { slug: "the-new-woo", title: "The New Woo", awards: 0, note: "In pre-production", year: 2026 },
] as const;

/** Derived so the front door and the films page can never drift apart. */
export const FILM_AWARDS = FILMS.reduce((n, f) => n + f.awards, 0);

/** The four intent lanes on the front door — each a pre-filtered Library view. */
export const LANES = [
  {
    href: "/fampire/library?kind=headshots",
    label: "Book them",
    detail: "Bios, headshots and the introduction an MC reads out loud.",
  },
  {
    href: "/fampire/library?kind=press",
    label: "Write about them",
    detail: "Synopses, award counts, press coverage and approved copy.",
  },
  {
    href: "/fampire/library?kind=b-roll",
    label: "Clip them",
    detail: "B-roll, trailers and cut recaps, straight into the timeline.",
  },
  {
    href: "/fampire/library?kind=event+photography",
    label: "Stage them",
    detail: "Event photography, galleries and logo packs for the room.",
  },
] as const;

/**
 * The best available picture for a person, film or event — the highest-signal
 * entry that carries one. Ordered so a headshot folder beats a b-roll dump and
 * key art beats a master folder, which is what makes a lens page look composed
 * rather than assembled from whatever happened to have a thumbnail.
 */
const KIND_RANK: Record<string, number> = {
  headshots: 0,
  poster: 1,
  "event photography": 2,
  trailer: 3,
  magazine: 4,
  BTS: 5,
  "b-roll": 6,
};

function bestOf(entries: Entry[]): Entry | null {
  const withImage = entries.filter((e) => e.image);
  if (!withImage.length) return null;
  return [...withImage].sort(
    (a, b) => (KIND_RANK[a.kind] ?? 9) - (KIND_RANK[b.kind] ?? 9),
  )[0];
}

/**
 * Previews for a row of people, guaranteed distinct.
 *
 * Love and Legend share a bio-and-headshots folder, so asking for each one's
 * best picture independently returns the same frame twice — which on a
 * four-up row reads as a bug, not as a shared source. Walk each subject's
 * candidates (best entry first, then the other frames from that folder's
 * contact strip, then the next entry) and take the first not already spent.
 */
export function previewsForSubjects(subjects: readonly string[]): Record<string, string | null> {
  const used = new Set<string>();
  const out: Record<string, string | null> = {};

  for (const subject of subjects) {
    const pool = ENTRIES.filter((e) => e.subjects.includes(subject) && e.image).sort(
      (a, b) => (KIND_RANK[a.kind] ?? 9) - (KIND_RANK[b.kind] ?? 9),
    );

    const candidates: string[] = [];
    for (const e of pool) {
      if (e.image) candidates.push(e.image);
      // Strip frames come from the same folder, so a sibling headshot is a
      // better second choice than a picture from an unrelated collection.
      for (const frame of e.strip) candidates.push(frame);
    }

    const pick = candidates.find((c) => !used.has(normalizeFrame(c))) ?? candidates[0] ?? null;
    if (pick) used.add(normalizeFrame(pick));
    out[subject] = pick;
  }

  return out;
}

/** The same Drive file appears at several widths across `image` and `strip`;
 *  compare on the id so those count as one picture, not four. */
function normalizeFrame(url: string): string {
  return url.replace(/([?&])sz=w\d+/, "$1sz=x");
}

export const previewForFilm = (film: string) =>
  bestOf(ENTRIES.filter((e) => e.film === film));

export function stats() {
  const pub = PUBLIC_ENTRIES.length;
  const films = new Set(ENTRIES.map((e) => e.film).filter(Boolean)).size;
  const events = new Set(ENTRIES.map((e) => e.event).filter(Boolean)).size;
  return { total: ENTRIES.length, pub, films, events, watch: WHERE_TO_WATCH.length };
}
