import type { Metadata } from "next";
import Link from "next/link";
import { ImageWell } from "@/components/fampire/Preview";
import appearancesJson from "@/data/fampire/appearances.json";
import previewsJson from "@/data/fampire/previews.json";

/**
 * The Press log — every appearance the family has made, with the date, the
 * host, the audience where the client recorded one, and the episode's own
 * thumbnail.
 *
 * Generated by scripts/fampire/build-appearances.mjs from the client's own
 * media-kit page and scripts/fampire/build-previews.mjs from each platform's
 * thumbnail service, so re-capturing that page adds new appearances without
 * anyone editing this file.
 */

export const metadata: Metadata = {
  title: "Press",
  description:
    "Every recorded podcast, broadcast and press appearance by Anthony and TereZa Lolli — dated, credited and linked.",
};

export const dynamic = "force-static";

type Appearance = {
  title: string;
  url: string;
  host: string | null;
  aired: string | null;
  views: number | null;
  views_as_of?: string | null;
  parts: { label: string; url: string }[];
};

const APPEARANCES = (appearancesJson as { appearances: Appearance[] }).appearances;
const PREVIEWS = (previewsJson as { previews: Record<string, { image: string | null }> })
  .previews;

/** Dates arrive as prose ("Feb 24, 2026", "June 5, 2025"), so parse leniently
 *  and push anything unparseable to the end rather than guessing a position. */
function airedTime(a: Appearance): number {
  if (!a.aired) return -Infinity;
  const t = Date.parse(a.aired);
  return Number.isNaN(t) ? -Infinity : t;
}

const sorted = [...APPEARANCES].sort((a, b) => airedTime(b) - airedTime(a));

/** The most-watched appearances lead the page — a booker scanning for reach
 *  should not have to read 57 rows to find the 506,000-view one. */
const FEATURED = [...APPEARANCES]
  .filter((a) => a.views && PREVIEWS[`press:${a.url}`]?.image)
  .sort((a, b) => (b.views ?? 0) - (a.views ?? 0))
  .slice(0, 3);
const featuredUrls = new Set(FEATURED.map((a) => a.url));

const totalViews = APPEARANCES.reduce((n, a) => n + (a.views ?? 0), 0);
const counted = APPEARANCES.filter((a) => a.views).length;
const fmt = new Intl.NumberFormat("en-US");

export default function PressPage() {
  return (
    <div className="mx-auto max-w-[1320px] px-6 pb-32 pt-12 sm:px-10 sm:pt-16 lg:px-12">
      <h1 className="fam-display text-[3rem] leading-[1.06] sm:text-[4.5rem]">Press</h1>
      <p className="mt-6 max-w-2xl text-[16.5px] leading-[1.65] text-fam-body">
        {APPEARANCES.length} recorded appearances. Where the client logged an
        audience figure it is reproduced here as written —{" "}
        <span className="font-semibold text-fam-ink">{fmt.format(totalViews)}</span>{" "}
        views across the {counted} that carry one.
      </p>

      {FEATURED.length > 0 ? (
        <section className="fam-section-rule mt-16 pt-6">
          <h2 className="fam-eyebrow">Most watched</h2>
          <ul className="mt-8 grid gap-x-8 gap-y-10 sm:grid-cols-3">
            {FEATURED.map((a) => (
              <li key={a.url}>
                <a
                  href={a.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="group block"
                >
                  <ImageWell
                    src={PREVIEWS[`press:${a.url}`]?.image ?? null}
                    alt={a.title}
                    label={a.title}
                    shape="cinema"
                    width={800}
                  />
                  <p className="fam-eyebrow-muted mt-4">
                    {a.aired} · {fmt.format(a.views ?? 0)} views
                  </p>
                  <h3 className="fam-display-sm mt-2 text-[18px] leading-snug">
                    {a.title}
                  </h3>
                  {a.host ? (
                    <p className="mt-1 text-[14px] text-fam-muted">with {a.host}</p>
                  ) : null}
                </a>
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      <section className="fam-section-rule mt-20 pt-6">
        <h2 className="fam-eyebrow">The full log</h2>
        <ul className="mt-6">
          {sorted.map((a) => {
            const thumb = PREVIEWS[`press:${a.url}`]?.image ?? null;
            return (
              <li key={a.url}>
                <a
                  href={a.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="fam-card group grid items-center gap-x-6 gap-y-2 py-5 sm:grid-cols-[5.5rem_1fr_9rem_7rem]"
                >
                  {/* A 88px still per row: enough to recognise a show at a
                      glance, not enough to turn a 57-row log into a gallery. */}
                  <div className="w-[5.5rem] shrink-0">
                    <ImageWell
                      src={thumb}
                      alt={a.title}
                      label={a.title.slice(0, 2)}
                      shape="cinema"
                      width={220}
                    />
                  </div>
                  <span>
                    <span className="fam-display-sm text-[17px] leading-snug">
                      {a.title}
                    </span>
                    {a.host ? (
                      <span className="ml-2 text-[14px] text-fam-muted">
                        with {a.host}
                      </span>
                    ) : null}
                    {a.parts.length > 1 ? (
                      <span className="ml-2 text-[11px] font-bold uppercase tracking-[0.1em] text-fam-faint">
                        {a.parts.length} parts
                      </span>
                    ) : null}
                    {featuredUrls.has(a.url) ? (
                      <span className="ml-2 border border-fam-ink px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-[0.1em] text-fam-ink">
                        Top
                      </span>
                    ) : null}
                  </span>
                  <span className="text-[13px] font-medium tabular-nums text-fam-muted sm:text-right">
                    {a.aired ?? "—"}
                  </span>
                  <span className="text-[13px] tabular-nums text-fam-faint sm:text-right">
                    {a.views ? `${fmt.format(a.views)} views` : ""}
                  </span>
                </a>
              </li>
            );
          })}
        </ul>
        <div className="border-t border-fam-rule" />
      </section>

      <p className="mt-10 max-w-2xl text-[13.5px] leading-relaxed text-fam-muted">
        Looking for something to clip rather than something to read?{" "}
        <Link
          href="/fampire/library?kind=b-roll"
          className="fam-underline font-semibold text-fam-ink"
        >
          The b-roll collections
        </Link>{" "}
        are in the library, filtered and one click from the source folder.
      </p>
    </div>
  );
}
